import type { GtmDataset } from "./gtm-types";

const DAY = 24 * 60 * 60 * 1000;
export const GTM_DEMO_NOW_MILLIS = new Date("2026-07-24T12:00:00.000Z").getTime();

export function buildGtmDemoDataset(nowMillis: number): GtmDataset {
  return {
    insights: [
      {
        id: "00000000-0000-4000-8000-000000000101",
        createdAtMillis: nowMillis - 14 * DAY,
        updatedAtMillis: nowMillis - 2 * DAY,
        domain: "users",
        kind: "segment_lift",
        status: "surfaced",
        confidence: "high",
        title: "Demo-land users are 1.9x more likely to become multi-day active",
        body: "Users from Demo-land become multi-day active at 56.3% versus a 29% baseline (n=96). The result survived false-discovery correction and replicated across both analysis windows.",
        impactScore: 82,
        timesSeen: 2,
        lastSeenAtMillis: nowMillis - 2 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000102",
        createdAtMillis: nowMillis - 14 * DAY,
        updatedAtMillis: nowMillis - 2 * DAY,
        domain: "revenue",
        kind: "funnel_dropoff",
        status: "surfaced",
        confidence: "medium",
        title: "62% of pricing-page visitors never reach checkout",
        body: "Of 240 users who viewed the pricing page, only 91 reached checkout. This step loses more users than any other part of the purchase funnel.",
        impactScore: 74,
        timesSeen: 2,
        lastSeenAtMillis: nowMillis - 2 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000103",
        createdAtMillis: nowMillis - 7 * DAY,
        updatedAtMillis: nowMillis - 2 * DAY,
        domain: "ads",
        kind: "segment_lift",
        status: "surfaced",
        confidence: "medium",
        title: "Retargeting brings the highest-quality trial traffic",
        body: "Retargeting visitors reached multi-day activity at 31% versus 18% for the other paid campaigns (n=186). This is based on simulated campaign data until a real ad account is connected.",
        impactScore: 66,
        timesSeen: 1,
        lastSeenAtMillis: nowMillis - 2 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000104",
        createdAtMillis: nowMillis - 14 * DAY,
        updatedAtMillis: nowMillis - 2 * DAY,
        domain: "revenue",
        kind: "checkout_abandonment",
        status: "surfaced",
        confidence: "medium",
        title: "23 started checkouts were abandoned in the last 30 days",
        body: "Twenty-three users created a purchase URL more than 24 hours ago and never completed it. Nineteen of them have marketing consent and can receive a recovery email.",
        impactScore: 68,
        timesSeen: 3,
        lastSeenAtMillis: nowMillis - 2 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000105",
        createdAtMillis: nowMillis - 7 * DAY,
        updatedAtMillis: nowMillis - 2 * DAY,
        domain: "outreach",
        kind: "send_time",
        status: "surfaced",
        confidence: "medium",
        title: "Emails sent at 18:00 local open at twice the morning rate",
        body: "Marketing emails delivered around 18:00 recipient-local time opened at 44%, compared with 21% for morning sends. Both groups cleared the minimum sample threshold.",
        impactScore: 61,
        timesSeen: 1,
        lastSeenAtMillis: nowMillis - 2 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000106",
        createdAtMillis: nowMillis - 14 * DAY,
        updatedAtMillis: nowMillis - 2 * DAY,
        domain: "product",
        kind: "friction_hotspot",
        status: "surfaced",
        confidence: "medium",
        title: "The Export button dead-clicks 47% of the time",
        body: "The Export button on the dashboard produced no visible effect for 60 of 128 clicks, far above the 9% site-wide baseline. Its disabled state likely looks interactive.",
        impactScore: 58,
        timesSeen: 2,
        lastSeenAtMillis: nowMillis - 2 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000107",
        createdAtMillis: nowMillis - 7 * DAY,
        updatedAtMillis: nowMillis - 2 * DAY,
        domain: "outreach",
        kind: "qualitative_theme",
        status: "new",
        confidence: "low",
        title: "Developer communities keep asking for teardown-style demo sessions",
        body: "Four of 11 sampled community conversations asked how other teams structure convincing product demos. A practical teardown event could answer that demand without becoming a sales pitch.",
        impactScore: 53,
        timesSeen: 1,
        lastSeenAtMillis: nowMillis - 2 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000108",
        createdAtMillis: nowMillis - 7 * DAY,
        updatedAtMillis: nowMillis - 2 * DAY,
        domain: "product",
        kind: "qualitative_theme",
        status: "new",
        confidence: "low",
        title: "Feature requests cluster around scheduled demo exports",
        body: "Five of 14 recent support conversations asked to schedule or automatically refresh exported demos. Validate the workflow before committing to a build.",
        impactScore: 49,
        timesSeen: 1,
        lastSeenAtMillis: nowMillis - 2 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000109",
        createdAtMillis: nowMillis - 14 * DAY,
        updatedAtMillis: nowMillis - 2 * DAY,
        domain: "content",
        kind: "funnel_dropoff",
        status: "surfaced",
        confidence: "medium",
        title: "SEO visitors who read the setup docs activate at 31%",
        body: "Organic visitors who continued from the integration guide into setup activated at 31% (44 of 142), versus 14% for visitors who skipped the docs (19 of 136).",
        impactScore: 63,
        timesSeen: 2,
        lastSeenAtMillis: nowMillis - 2 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000110",
        createdAtMillis: nowMillis - 21 * DAY,
        updatedAtMillis: nowMillis - 9 * DAY,
        domain: "users",
        kind: "retention",
        status: "acknowledged",
        confidence: "medium",
        title: "Retention flattens at 22% and newer cohorts are improving",
        body: "Weekly cohorts settle at roughly 22% long-run retention instead of decaying to zero. Newer cohorts are trending slightly above the older baseline.",
        impactScore: 55,
        timesSeen: 2,
        lastSeenAtMillis: nowMillis - 9 * DAY,
      },
    ],
    actions: [
      {
        id: "00000000-0000-4000-8000-000000000201",
        createdAtMillis: nowMillis - 30 * 60 * 1000,
        updatedAtMillis: nowMillis - 30 * 60 * 1000,
        domain: "revenue",
        type: "checkout_recovery_email",
        status: "proposed",
        title: "Recover abandoned demo-workspace checkouts",
        summary: "Send a short recovery email at 18:00 local time to the 19 consented users who left setup unfinished, with a 20% holdout for measurement.",
        verdict: null,
        retrospective: null,
        expiresAtMillis: nowMillis + 14 * DAY,
        executedAtMillis: null,
      },
      {
        id: "00000000-0000-4000-8000-000000000202",
        createdAtMillis: nowMillis - 24 * DAY,
        updatedAtMillis: nowMillis - 15 * DAY,
        domain: "revenue",
        type: "checkout_recovery_email",
        status: "executed",
        title: "Remind buyers that their demo plan is waiting",
        summary: "Send a plan-specific checkout reminder in the evening and reserve a holdout group.",
        verdict: "worked",
        retrospective: "The treatment converted 26 of 118 recipients, versus 2 of 30 in the holdout. Referencing the abandoned plan and matching the evening activity window are both worth repeating.",
        expiresAtMillis: nowMillis - 10 * DAY,
        executedAtMillis: nowMillis - 23 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000203",
        createdAtMillis: nowMillis - 21 * DAY,
        updatedAtMillis: nowMillis - 12 * DAY,
        domain: "outreach",
        type: "broadcast_email",
        status: "executed",
        title: "Send a broad product newsletter",
        summary: "Test a general product-news update against a no-send holdout.",
        verdict: "didnt_work",
        retrospective: "The generic newsletter converted 3 of 160 recipients, while the holdout converted 5 of 40. Broad sends without a concrete hook hurt more than they help for this audience.",
        expiresAtMillis: nowMillis - 7 * DAY,
        executedAtMillis: nowMillis - 20 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000204",
        createdAtMillis: nowMillis - 18 * DAY,
        updatedAtMillis: nowMillis - 9 * DAY,
        domain: "outreach",
        type: "broadcast_email",
        status: "executed",
        title: "Spotlight the demo dashboard",
        summary: "Test a focused feature email about demo dashboards against a no-send holdout.",
        verdict: "inconclusive",
        retrospective: "Treatment converted at 8.0% and holdout at 7.9%. The feature angle neither helped nor hurt, so it is not worth repeating without a stronger hook.",
        expiresAtMillis: nowMillis - 4 * DAY,
        executedAtMillis: nowMillis - 17 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000205",
        createdAtMillis: nowMillis - 13 * DAY,
        updatedAtMillis: nowMillis - 4 * DAY,
        domain: "revenue",
        type: "checkout_recovery_email",
        status: "executed",
        title: "Test a softer checkout reminder",
        summary: "Ask undecided buyers whether they are still considering the plan, using a small holdout.",
        verdict: "worked",
        retrospective: "The treatment recovered 11 of 47 checkouts against none of 9 in the holdout. This is directionally strong, but the holdout is too small for a firm conclusion.",
        expiresAtMillis: nowMillis + DAY,
        executedAtMillis: nowMillis - 12 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000206",
        createdAtMillis: nowMillis - 11 * DAY,
        updatedAtMillis: nowMillis - 10 * DAY,
        domain: "product",
        type: "config_change",
        status: "executed",
        title: "Switch lifecycle emails to the dark theme",
        summary: "Align lifecycle email styling with the product's visual identity.",
        verdict: "never_measured",
        retrospective: "The theme now matches the product, but a configuration switch has no holdout and cannot be attributed to an outcome.",
        expiresAtMillis: nowMillis + 3 * DAY,
        executedAtMillis: nowMillis - 11 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000207",
        createdAtMillis: nowMillis - 10 * DAY,
        updatedAtMillis: nowMillis - 9 * DAY,
        domain: "outreach",
        type: "broadcast_email",
        status: "rejected",
        title: "Offer an aggressive discount",
        summary: "Send a discount-led broadcast to inactive trial users.",
        verdict: "rejected_by_you",
        retrospective: "Rejected during review because the company strategy explicitly rules out discounting. Future proposals should use value-led angles.",
        expiresAtMillis: nowMillis + 4 * DAY,
        executedAtMillis: null,
      },
      {
        id: "00000000-0000-4000-8000-000000000208",
        createdAtMillis: nowMillis - 30 * DAY,
        updatedAtMillis: nowMillis - 16 * DAY,
        domain: "revenue",
        type: "checkout_recovery_email",
        status: "expired",
        title: "Send a last-chance setup reminder",
        summary: "Prompt abandoned buyers to finish setup before their plan expires.",
        verdict: "expired",
        retrospective: null,
        expiresAtMillis: nowMillis - 16 * DAY,
        executedAtMillis: null,
      },
    ],
    notes: [
      {
        id: "00000000-0000-4000-8000-000000000301",
        createdAtMillis: nowMillis - 30 * DAY,
        updatedAtMillis: nowMillis - 7 * DAY,
        domain: "product",
        category: "company",
        title: "Product positioning",
        body: "Demo Project sells a collaborative demo-building tool. Its positioning is “ship a convincing demo in an afternoon.”",
        source: "run",
        lastConfirmedAtMillis: nowMillis - 7 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000302",
        createdAtMillis: nowMillis - 30 * DAY,
        updatedAtMillis: nowMillis - 7 * DAY,
        domain: "users",
        category: "audience",
        title: "Ideal customer profile",
        body: "The ideal customers are developer-founders at seed-stage startups, and most signups come from developer communities.",
        source: "chat",
        lastConfirmedAtMillis: nowMillis - 7 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000303",
        createdAtMillis: nowMillis - 30 * DAY,
        updatedAtMillis: nowMillis - 10 * DAY,
        domain: "revenue",
        category: "strategy",
        title: "Discount-free positioning",
        body: "The founder does not want to use discounts. Campaigns should lead with concrete product value instead.",
        source: "user",
        lastConfirmedAtMillis: nowMillis - 10 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000304",
        createdAtMillis: nowMillis - 30 * DAY,
        updatedAtMillis: nowMillis - 12 * DAY,
        domain: "outreach",
        category: "user_preference",
        title: "Outreach preferences",
        body: "Prefer evening send times and concise emails that feel like plain text.",
        source: "user",
        lastConfirmedAtMillis: nowMillis - 12 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000305",
        createdAtMillis: nowMillis - 30 * DAY,
        updatedAtMillis: nowMillis - 15 * DAY,
        domain: "revenue",
        category: "learning",
        title: "Checkout recovery learning",
        body: "Checkout-recovery emails that reference the abandoned plan outperformed a generic reminder by 19 percentage points.",
        source: "run",
        lastConfirmedAtMillis: nowMillis - 15 * DAY,
      },
      {
        id: "00000000-0000-4000-8000-000000000306",
        createdAtMillis: nowMillis - 30 * DAY,
        updatedAtMillis: nowMillis - 13 * DAY,
        domain: "outreach",
        category: "learning",
        title: "Newsletter performance",
        body: "Broad newsletters without a concrete hook underperform the holdout for this audience.",
        source: "run",
        lastConfirmedAtMillis: nowMillis - 13 * DAY,
      },
    ],
    radar: new Map([
      ["product", 69],
      ["users", 78],
      ["ads", 64],
      ["revenue", 74],
      ["outreach", 71],
      ["content", 67],
    ]),
  };
}
