// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddManualQaReducer from "../add_manual_qa_reducer";
import DeleteQaEntryReducer from "../delete_qa_entry_reducer";
import LogMcpCallReducer from "../log_mcp_call_reducer";
import MarkHumanReviewedReducer from "../mark_human_reviewed_reducer";
import UpdateHumanCorrectionReducer from "../update_human_correction_reducer";
import UpdateMcpQaReviewReducer from "../update_mcp_qa_review_reducer";

export type AddManualQaParams = __Infer<typeof AddManualQaReducer>;
export type DeleteQaEntryParams = __Infer<typeof DeleteQaEntryReducer>;
export type LogMcpCallParams = __Infer<typeof LogMcpCallReducer>;
export type MarkHumanReviewedParams = __Infer<typeof MarkHumanReviewedReducer>;
export type UpdateHumanCorrectionParams = __Infer<typeof UpdateHumanCorrectionReducer>;
export type UpdateMcpQaReviewParams = __Infer<typeof UpdateMcpQaReviewReducer>;

