import { flyConfig, MOCK_FLY_TOKEN } from "../config.js";
import { PROVIDER_MUTATION_TIMEOUT_MS, PROVIDER_READ_TIMEOUT_MS, MutationOutcomeUnknownError } from "../mutation-safety.js";

// Thin client for the three Fly API surfaces Marshal talks to, plus the Docker registry.
// One instance per (org, token) — resolved per namespace via resolveNamespaceOrg.
//
// Auth quirk (smoke-verified): the Machines REST API and GraphQL accept
// "Authorization: Bearer <token>", but the logs API only accepts the raw macaroon scheme
// ("Authorization: FlyV1 fm2_..."), i.e. the token verbatim.

export class FlyApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly endpoint: string,
    public readonly flyMessage: string,
  ) {
    super(`Fly API error at ${endpoint}: ${status} ${flyMessage}`);
    this.name = "FlyApiError";
  }
}

export type FlyMachine = {
  id: string,
  name: string,
  state: string,
  region: string,
  instance_id: string,
  // What Fly RESOLVED the machine's image to. Present on create, update and
  // list. A spec may name a tag, and this is the digest that tag pointed at when
  // Fly pulled it — the only place the running bytes are recorded, since Marshal
  // does not resolve images itself.
  //
  // Only `digest` is used, and only through pinToDigest. `registry`/`repository`
  // describe Fly's own fetch, not the author's reference: a Docker Hub image
  // reports `docker-hub-mirror.fly.io` (smoke-verified). The digest of a
  // multi-platform image is the linux/amd64 manifest, not the index.
  image_ref?: {
    registry?: string,
    repository?: string,
    tag?: string,
    digest?: string,
  },
  config: {
    image: string,
    env?: Record<string, string>,
    metadata?: Record<string, string>,
    mounts?: { volume: string, path: string }[],
    [key: string]: unknown,
  },
};

export type FlyLogEntry = {
  id: string,
  attributes: {
    timestamp: string,
    message: string,
    level: string,
    instance: string | null,
    region: string,
    meta?: { event?: { provider?: string } | null } | null,
  },
};

export type FlyCertificate = {
  id: string,
  hostname: string,
  configured: boolean,
  acmeDnsConfigured: boolean,
  clientStatus: string,
  dnsValidationHostname: string,
  dnsValidationTarget: string,
  isApex: boolean,
  issued: { nodes: { type: string, expiresAt: string }[] },
};

export type FlyVolume = {
  id: string,
  name: string,
  state: string,
  size_gb: number,
  region: string,
  attached_machine_id: string | null,
};

export type FlyAppIps = {
  sharedIpv4: string | null,
  dedicated: { id: string, address: string, type: string }[],
};

// Builds a Machines API path with every interpolated segment percent-encoded, so a value
// containing "/", "?" or "#" cannot change the target path or smuggle in query parameters.
// Static text in the template — the route separators, and any literal query string — is left
// alone, which is what keeps `?force=true` working. App names are generated by naming.ts and
// machine/volume ids come back from Fly, so this is defense in depth rather than a live hole;
// it is also what the repo's URL guideline asks for instead of bare interpolation.
function flyPath(strings: TemplateStringsArray, ...values: (string | number)[]): string {
  return strings.reduce<string>(
    (acc, part, index) => acc + part + (index < values.length ? encodeURIComponent(values[index]) : ""),
    "",
  );
}

export class FlyClient {
  constructor(
    private readonly token: string,
    public readonly orgSlug: string,
  ) {}

  // A read has no body to re-send, so retry it once on a network-level failure (undici
  // surfaces a keep-alive socket reset as a TypeError). Writes are never retried here — a
  // duplicated machine create is worse than a surfaced error.
  private async retryReadOnSocketReset(doFetch: () => Promise<Response>): Promise<Response> {
    try {
      return await doFetch();
    } catch (error) {
      if (!(error instanceof TypeError)) throw error;
      return await doFetch();
    }
  }

  private async fetchWithReadRetry(url: string, init: RequestInit & { method: string }): Promise<Response> {
    if (init.method === "GET" || init.method === "HEAD") {
      // Reads are bounded too — see PROVIDER_READ_TIMEOUT_MS. A fresh signal per attempt, because
      // an AbortSignal.timeout that already fired would abort the retry instantly.
      return await this.retryReadOnSocketReset(() => fetch(url, { ...init, signal: AbortSignal.timeout(PROVIDER_READ_TIMEOUT_MS) }));
    }
    try {
      return await fetch(url, { ...init, signal: AbortSignal.timeout(PROVIDER_MUTATION_TIMEOUT_MS) });
    } catch (error) {
      // A failed write request can have reached Fly even when no response reached Marshal.
      // Keep the lease until expiry+drain so a replacement cannot overlap that operation.
      throw new MutationOutcomeUnknownError(`Fly mutation ${init.method} ${url} ended without a response`, { cause: error });
    }
  }

  private async readResponseText(response: Response, unknownMutationDescription: string | null): Promise<string> {
    try {
      return await response.text();
    } catch (error) {
      if (unknownMutationDescription === null) throw error;
      // fetch() resolves as soon as response headers arrive. A later body reset/timeout still
      // leaves the write's outcome uncertain and therefore requires the same lease drain.
      throw new MutationOutcomeUnknownError(`${unknownMutationDescription} response ended before its body was received`, { cause: error });
    }
  }

  private async fetchMachinesApi<T>(path: string, init?: { method?: string, body?: unknown, allow404?: boolean }): Promise<T | null> {
    const fly = flyConfig();
    const method = init?.method ?? "GET";
    const response = await this.fetchWithReadRetry(`${fly.machinesApiUrl}/v1${path}`, {
      method,
      headers: {
        "authorization": `Bearer ${this.token}`,
        ...(init?.body !== undefined ? { "content-type": "application/json" } : {}),
      },
      body: init?.body !== undefined ? JSON.stringify(init.body) : undefined,
    });
    const text = await this.readResponseText(
      response,
      method === "GET" || method === "HEAD" ? null : `Fly mutation ${method} ${path}`,
    );
    if (response.status === 404 && init?.allow404) {
      return null;
    }
    if (!response.ok) {
      let message = text.slice(0, 500);
      try {
        message = (JSON.parse(text) as { error?: string }).error ?? message;
      } catch {
        // non-JSON error body; keep the raw text
      }
      throw new FlyApiError(response.status, `machines ${init?.method ?? "GET"} ${path}`, message);
    }
    return text === "" ? null : JSON.parse(text) as T;
  }

  // allowNotFound: real Fly answers reads on nonexistent apps with a
  // "Could not find App" GraphQL error (not a null app); the read paths treat
  // that as "no data" so a service without an app reads as empty.
  private async fetchGraphql<T>(query: string, variables: Record<string, unknown>, options?: { allowNotFound?: boolean, read?: boolean }): Promise<T | null> {
    const fly = flyConfig();
    const doFetch = () => fetch(fly.graphqlApiUrl, {
      method: "POST",
      headers: { "authorization": `Bearer ${this.token}`, "content-type": "application/json" },
      body: JSON.stringify({ query, variables }),
      // Both are bounded, at different limits: a write's timeout is what the reconciliation
      // takeover grace is derived from, while a read only has to not hang forever.
      signal: AbortSignal.timeout(options?.read ? PROVIDER_READ_TIMEOUT_MS : PROVIDER_MUTATION_TIMEOUT_MS),
    });
    // Read queries get the same one-shot socket-reset retry the REST reads get.
    let response: Response;
    try {
      response = options?.read ? await this.retryReadOnSocketReset(doFetch) : await doFetch();
    } catch (error) {
      if (options?.read) throw error;
      throw new MutationOutcomeUnknownError("Fly GraphQL mutation ended without a response", { cause: error });
    }
    // Read as text and parse defensively: a non-JSON upstream body (a proxy's 502 HTML page)
    // must surface as a FlyApiError(502-ish), not a bare SyntaxError → generic 500.
    const text = await this.readResponseText(response, options?.read ? null : "Fly GraphQL mutation");
    let json: { data?: T, errors?: { message: string }[] };
    try {
      json = JSON.parse(text) as { data?: T, errors?: { message: string }[] };
    } catch {
      throw new FlyApiError(response.status, "graphql", text.slice(0, 500) || `HTTP ${response.status} (non-JSON body)`);
    }
    const errors = json.errors ?? [];
    if (options?.allowNotFound && errors.length > 0 && errors.every((error) => /could not find/i.test(error.message))) {
      return null;
    }
    if (!response.ok || errors.length > 0) {
      throw new FlyApiError(response.status, "graphql", errors.map((e) => e.message).join("; ") || `HTTP ${response.status}`);
    }
    return json.data as T;
  }

  // -------------------------------------------------------------------------
  // Apps

  async getApp(name: string): Promise<{ name: string, status: string } | null> {
    return await this.fetchMachinesApi<{ name: string, status: string }>(flyPath`/apps/${name}`, { allow404: true });
  }

  async createApp(name: string, network: string): Promise<void> {
    await this.fetchMachinesApi(`/apps`, {
      method: "POST",
      body: { app_name: name, org_slug: this.orgSlug, network },
    });
  }

  async ensureApp(name: string, network: string): Promise<void> {
    const existing = await this.getApp(name);
    if (existing !== null) return;
    try {
      await this.createApp(name, network);
    } catch (error) {
      // Lost a create race — the app now existing is the state we wanted.
      if (error instanceof FlyApiError && (error.status === 409 || error.status === 422) && (await this.getApp(name)) !== null) return;
      throw error;
    }
  }

  async deleteApp(name: string): Promise<void> {
    await this.fetchMachinesApi(flyPath`/apps/${name}` + "?force=true", { method: "DELETE", allow404: true });
  }

  // -------------------------------------------------------------------------
  // Machines

  async listMachines(app: string): Promise<FlyMachine[]> {
    return await this.fetchMachinesApi<FlyMachine[]>(flyPath`/apps/${app}/machines`, { allow404: true }) ?? [];
  }

  async getMachine(app: string, machineId: string): Promise<FlyMachine | null> {
    return await this.fetchMachinesApi<FlyMachine>(flyPath`/apps/${app}/machines/${machineId}`, { allow404: true });
  }

  async createMachine(app: string, body: { name?: string, region: string, config: Record<string, unknown> }): Promise<FlyMachine> {
    const machine = await this.fetchMachinesApi<FlyMachine>(flyPath`/apps/${app}/machines`, { method: "POST", body });
    if (machine === null) throw new FlyApiError(500, `machines POST /apps/${app}/machines`, "empty response");
    return machine;
  }

  async updateMachine(app: string, machineId: string, config: Record<string, unknown>): Promise<FlyMachine> {
    const machine = await this.fetchMachinesApi<FlyMachine>(flyPath`/apps/${app}/machines/${machineId}`, { method: "POST", body: { config } });
    if (machine === null) throw new FlyApiError(500, `machines POST /apps/${app}/machines/${machineId}`, "empty response");
    return machine;
  }

  async destroyMachine(app: string, machineId: string): Promise<void> {
    await this.fetchMachinesApi(flyPath`/apps/${app}/machines/${machineId}` + "?force=true", { method: "DELETE", allow404: true });
  }

  async startMachine(app: string, machineId: string): Promise<void> {
    await this.fetchMachinesApi(flyPath`/apps/${app}/machines/${machineId}/start`, { method: "POST" });
  }

  // The /wait endpoint caps timeout at 60s (smoke-verified: larger values → 400), so waits
  // longer than that loop here.
  async waitForMachineState(app: string, machineId: string, state: "started" | "stopped" | "destroyed", options?: { instanceId?: string, totalTimeoutSeconds?: number }): Promise<void> {
    const deadline = Date.now() + (options?.totalTimeoutSeconds ?? 60) * 1000;
    for (;;) {
      const remainingSeconds = Math.ceil((deadline - Date.now()) / 1000);
      // Don't start another wait once the deadline has passed (a fast-returning 408 could
      // otherwise loop tightly against the API for the whole budget).
      if (remainingSeconds <= 0) throw new FlyApiError(408, `machines wait /apps/${app}/machines/${machineId}`, `timed out waiting for state ${state}`);
      const params = new URLSearchParams({ state, timeout: String(Math.min(60, remainingSeconds)) });
      if (options?.instanceId !== undefined) params.set("instance_id", options.instanceId);
      try {
        await this.fetchMachinesApi(flyPath`/apps/${app}/machines/${machineId}/wait` + `?${params.toString()}`);
        return;
      } catch (error) {
        if (Date.now() >= deadline) throw error;
        // Timeout errors surface as 408; anything else is real.
        if (!(error instanceof FlyApiError) || error.status !== 408) throw error;
        // Small backoff so a proxy timing out ahead of Fly's own long-poll can't spin.
        await new Promise((resolve) => setTimeout(resolve, 1000));
      }
    }
  }

  // -------------------------------------------------------------------------
  // Volumes
  //
  // Smoke-verified against real Fly: a volume outlives machine destroy and
  // re-attaches to a new machine, but `DELETE /apps/{app}?force=true` destroys it with the
  // app. Creates answer 201, not 200.

  async listVolumes(app: string): Promise<FlyVolume[]> {
    return await this.fetchMachinesApi<FlyVolume[]>(flyPath`/apps/${app}/volumes`, { allow404: true }) ?? [];
  }

  async createVolume(app: string, body: { name: string, region: string, size_gb: number }): Promise<FlyVolume> {
    const volume = await this.fetchMachinesApi<FlyVolume>(flyPath`/apps/${app}/volumes`, { method: "POST", body });
    // The id is asserted, not just null-checked: without it the caller builds
    // `mounts: [{ volume: undefined, path }]`, whose `volume` key vanishes under
    // JSON.stringify, and Fly answers the machine create with a baffling error instead.
    if (volume === null || typeof volume.id !== "string" || volume.id === "") {
      throw new FlyApiError(500, `machines POST /apps/${app}/volumes`, "volume create response had no id");
    }
    return volume;
  }

  // A create can answer 201 before the volume is listable. Mounting one that Fly hasn't
  // surfaced yet fails with "volume does not exist", which on the add-a-volume path would
  // land AFTER the old machine was destroyed — i.e. downtime until a later reconcile.
  // Smoke runs have always seen it ready on the first poll, so this normally costs one
  // extra list; the bounded loop is insurance, not an expected wait.
  async waitForVolumeListed(app: string, volumeId: string, options?: { attempts?: number, delayMillis?: number }): Promise<void> {
    const attempts = options?.attempts ?? 10;
    for (let attempt = 0; attempt < attempts; attempt++) {
      const volumes = await this.listVolumes(app);
      if (volumes.some((volume) => volume.id === volumeId && volume.state !== "creating")) return;
      await new Promise((resolve) => setTimeout(resolve, options?.delayMillis ?? 1000));
    }
    // Don't throw: the machine create below is the real arbiter, and its error names the
    // actual problem. Failing here would turn a slow list into a failed deploy.
  }

  // Grow-only. Fly rejects a smaller size; callers reject it earlier with a better message.
  async extendVolume(app: string, volumeId: string, sizeGb: number): Promise<void> {
    await this.fetchMachinesApi(flyPath`/apps/${app}/volumes/${volumeId}/extend`, { method: "PUT", body: { size_gb: sizeGb } });
  }

  // -------------------------------------------------------------------------
  // IPs (GraphQL)

  async getAppIps(app: string): Promise<FlyAppIps> {
    const data = await this.fetchGraphql<{ app: { sharedIpAddress: string | null, ipAddresses: { nodes: { id: string, address: string, type: string }[] } } | null }>(`
      query($app: String!) {
        app(name: $app) { sharedIpAddress ipAddresses { nodes { id address type } } }
      }`, { app }, { allowNotFound: true, read: true });
    return {
      sharedIpv4: data?.app?.sharedIpAddress ?? null,
      dedicated: data?.app?.ipAddresses.nodes ?? [],
    };
  }

  async allocateIp(app: string, type: "shared_v4" | "v6" | "private_v6", network?: string): Promise<void> {
    await this.fetchGraphql(`
      mutation($input: AllocateIPAddressInput!) {
        allocateIpAddress(input: $input) { app { name } }
      }`, { input: { appId: app, type, ...(network !== undefined ? { network } : {}) } });
  }

  async releaseIpById(app: string, ipAddressId: string): Promise<void> {
    await this.fetchGraphql(`
      mutation($input: ReleaseIPAddressInput!) { releaseIpAddress(input: $input) { app { name } } }`,
      { input: { appId: app, ipAddressId } });
  }

  async releaseIpByAddress(app: string, ip: string): Promise<void> {
    await this.fetchGraphql(`
      mutation($input: ReleaseIPAddressInput!) { releaseIpAddress(input: $input) { app { name } } }`,
      { input: { appId: app, ip } });
  }

  async ensureFlycastIp(app: string, network: string): Promise<void> {
    const ips = await this.getAppIps(app);
    if (ips.dedicated.some((ip) => ip.type === "private_v6")) return;
    await this.allocateIp(app, "private_v6", network);
  }

  // -------------------------------------------------------------------------
  // Certificates (GraphQL)

  private static readonly CERTIFICATE_FIELDS = `
    id hostname configured acmeDnsConfigured clientStatus
    dnsValidationHostname dnsValidationTarget isApex
    issued { nodes { type expiresAt } }`;

  async addCertificate(app: string, hostname: string): Promise<FlyCertificate> {
    const data = await this.fetchGraphql<{ addCertificate: { certificate: FlyCertificate } }>(`
      mutation($appId: ID!, $hostname: String!) {
        addCertificate(appId: $appId, hostname: $hostname) {
          certificate { ${FlyClient.CERTIFICATE_FIELDS} }
        }
      }`, { appId: app, hostname });
    if (data === null) throw new FlyApiError(500, "graphql addCertificate", "empty response");
    return data.addCertificate.certificate;
  }

  async deleteCertificate(app: string, hostname: string): Promise<void> {
    try {
      await this.fetchGraphql(`
        mutation($appId: ID!, $hostname: String!) {
          deleteCertificate(appId: $appId, hostname: $hostname) { certificate { id } }
        }`, { appId: app, hostname });
    } catch (error) {
      // Deleting an already-gone certificate (or one on a deleted app) is a no-op.
      if (error instanceof FlyApiError && /not found|could not find/i.test(error.flyMessage)) return;
      throw error;
    }
  }

  async getCertificate(app: string, hostname: string): Promise<FlyCertificate | null> {
    const data = await this.fetchGraphql<{ app: { certificate: FlyCertificate | null } | null }>(`
      query($app: String!, $hostname: String!) {
        app(name: $app) { certificate(hostname: $hostname) { ${FlyClient.CERTIFICATE_FIELDS} } }
      }`, { app, hostname }, { allowNotFound: true, read: true });
    return data?.app?.certificate ?? null;
  }

  async listCertificates(app: string): Promise<FlyCertificate[]> {
    const data = await this.fetchGraphql<{ app: { certificates: { nodes: FlyCertificate[] } } | null }>(`
      query($app: String!) {
        app(name: $app) { certificates { nodes { ${FlyClient.CERTIFICATE_FIELDS} } } }
      }`, { app }, { allowNotFound: true, read: true });
    return data?.app?.certificates.nodes ?? [];
  }

  // -------------------------------------------------------------------------
  // Logs API

  async getLogs(app: string, options?: { nextToken?: string, instance?: string }): Promise<{ entries: FlyLogEntry[], nextToken: string | null }> {
    const fly = flyConfig();
    const params = new URLSearchParams();
    if (options?.nextToken !== undefined) params.set("next_token", options.nextToken);
    if (options?.instance !== undefined) params.set("instance", options.instance);
    const queryString = params.toString();
    const logsUrl = fly.logsApiUrl + flyPath`/apps/${app}/logs` + (queryString === "" ? "" : `?${queryString}`);
    // Through fetchWithReadRetry like every other read, so it gets the read timeout and the
    // socket-reset retry. A bare fetch here could hang the durable build-log drain forever.
    const response = await this.fetchWithReadRetry(logsUrl, {
      method: "GET",
      // Raw macaroon scheme — "Bearer" is rejected with a 401 here (smoke-verified).
      headers: { "authorization": this.token },
    });
    if (!response.ok) {
      await response.arrayBuffer();
      // The logs API answers 401 (and 404) BOTH for an app that doesn't exist and for
      // invalid or expired credentials, and gives no way to tell them apart. Returning
      // "no logs" for either used to hide a broken org token as an ordinary empty page —
      // and, worse, could silently truncate the one-shot durable build-log drain.
      //
      // So ask the Machines API, which does distinguish: 404 for a missing app, 401 for a
      // bad credential. Only a confirmed-absent app is "no logs"; anything else propagates.
      // Costs one extra round-trip, and only on a path that was going to return nothing.
      if (response.status === 401 || response.status === 404) {
        let appExists: boolean;
        try {
          appExists = (await this.getApp(app)) !== null;
        } catch (error) {
          // The probe itself failed — an auth failure, or the API being unreachable. Either
          // way we cannot claim the app is gone, so report the original logs failure.
          throw new FlyApiError(response.status, `logs GET /apps/${app}/logs`, `logs API returned ${response.status} and the app could not be confirmed missing (${error instanceof Error ? error.message : "unknown error"})`);
        }
        if (!appExists) return { entries: [], nextToken: null };
        throw new FlyApiError(response.status, `logs GET /apps/${app}/logs`, `logs API returned ${response.status} for an app that exists — the Fly credential is likely invalid or expired`);
      }
      throw new FlyApiError(response.status, `logs GET /apps/${app}/logs`, "logs API error");
    }
    const json = await response.json() as { data?: FlyLogEntry[], meta?: { next_token?: string } };
    return {
      entries: json.data ?? [],
      nextToken: json.meta?.next_token === undefined || json.meta.next_token === "" ? null : json.meta.next_token,
    };
  }

  // -------------------------------------------------------------------------
  // Docker registry (registry.fly.io speaks the standard v2 protocol; basic auth with
  // user "x" and the org token as password — smoke-verified, works with or without the
  // "FlyV1 " prefix)

  private registryAuthHeader(): string {
    return `Basic ${Buffer.from(`x:${this.token}`).toString("base64")}`;
  }

  registryAuthBase64(): string {
    return Buffer.from(`x:${this.token}`).toString("base64");
  }

  async resolveImageDigest(app: string, tag: string): Promise<string | null> {
    const fly = flyConfig();
    // The registry has no mock; when the mock Fly token is in use, don't send a real HTTPS
    // request to registry.fly.io with a sentinel credential (surprising egress + a 401 that
    // surfaces as "digest could not be resolved"). Mock builds always supply the digest in
    // their metadata, so this fallback is never legitimately reached under the mock.
    if (this.token === MOCK_FLY_TOKEN) return null;
    const response = await fetch(`https://${fly.registryHost}/v2/${encodeURIComponent(app)}/manifests/${tag}`, {
      method: "HEAD",
      headers: {
        "authorization": this.registryAuthHeader(),
        "accept": "application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json",
      },
    });
    await response.arrayBuffer();
    if (!response.ok) return null;
    return response.headers.get("docker-content-digest");
  }

  async deleteImageManifest(app: string, digest: string): Promise<void> {
    const fly = flyConfig();
    if (this.token === MOCK_FLY_TOKEN) return; // no mock registry — see resolveImageDigest
    const response = await fetch(`https://${fly.registryHost}/v2/${encodeURIComponent(app)}/manifests/${digest}`, {
      method: "DELETE",
      headers: { "authorization": this.registryAuthHeader() },
    });
    await response.arrayBuffer();
    // 404 = already gone; anything else non-2xx is unexpected but GC is best-effort.
  }
}

export function flyClientForNamespaceOrg(org: { orgSlug: string, token: string }): FlyClient {
  return new FlyClient(org.token, org.orgSlug);
}
