packages:
  - packages/*
  - apps/*
  - examples/*
  - docs
  - docs-mintlify
  - sdks/*
  - sdks/implementations/*

minimumReleaseAge: 10080

blockExoticSubdeps: true

allowBuilds:
  '@prisma/engines': true
  '@sentry/cli': true
  '@tailwindcss/oxide': true
  '@vercel/speed-insights': true
  bcrypt: true
  core-js: true
  esbuild: true
  iframe-resizer: false
  keytar: false
  prisma: true
  protobufjs: true
  puppeteer: true
  sharp: true
