packages:
  - packages/*
  - apps/*
  - examples/*
  - docs
  - docs-mintlify
  - sdks/*
  - sdks/implementations/*

minimumReleaseAge: 10080

blockExoticSubdeps: true

overrides:
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  sharp: ^0.34.5

packageExtensions:
  '@mintlify/link-rot':
    dependencies:
      react: '*'
      react-dom: '*'

patchedDependencies:
  openid-client@5.6.4: patches/openid-client@5.6.4.patch

allowBuilds:
  '@prisma/engines': true
  '@quetzallabs/i18n': false
  '@sentry/cli': true
  '@tailwindcss/oxide': true
  '@vercel/speed-insights': true
  bcrypt: true
  core-js: true
  esbuild: true
  iframe-resizer: false
  keytar: false
  prisma: true
  protobufjs: true
  puppeteer: true
  sharp: true
