import { writeFileSyncIfChanged } from '@stackframe/stack-shared/dist/utils/fs';
import { glob } from 'glob';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';

type TypeDefinitionFile = {
  path: string,
  content: string,
};

async function main() {
  console.log('[Bundle Type Definitions] Finding Stack SDK type definition files...');
  
  const rootPath = path.resolve(process.cwd(), '../..');
  const stackAppPath = path.join(rootPath, 'packages/template/src/lib/stack-app');
  const dashboardUITypesPath = path.join(rootPath, 'packages/dashboard-ui-components/dist/index.d.ts');
  const outputPath = path.join(rootPath, 'apps/dashboard/src/generated/bundled-type-definitions.ts');
  
  const files = await glob(`${stackAppPath}/**/*.ts`, {
    ignore: [
      `${stackAppPath}/**/implementations/**`,
      `${stackAppPath}/**/utils/**`,
      `${stackAppPath}/**/*.d.ts`,
      `${stackAppPath}/**/global.css`,
    ],
  });
  files.sort();
  
  console.log(`[Bundle Type Definitions] Found ${files.length} type definition files`);
  
  const bundledFiles: TypeDefinitionFile[] = [];
  
  for (const filePath of files) {
    const relativePath = path.relative(stackAppPath, filePath);
    const content = await fs.readFile(filePath, 'utf8');
    
    bundledFiles.push({
      path: relativePath,
      content,
    });
  }

  // Bundle dashboard-ui-components type declarations (auto-generated by tsup build)
  let dashboardUITypes = '';
  try {
    dashboardUITypes = await fs.readFile(dashboardUITypesPath, 'utf8');
    console.log(`[Bundle Type Definitions] Loaded dashboard-ui-components types (${(dashboardUITypes.length / 1024).toFixed(2)} KB)`);
  } catch {
    console.warn('[Bundle Type Definitions] Warning: dashboard-ui-components dist/index.d.ts not found. Run the package build first.');
  }
  
  console.log('[Bundle Type Definitions] Generating bundled-type-definitions.ts...');
  
  const output = `// This file is auto-generated by scripts/bundle-type-definitions.ts
// Do not edit manually - changes will be overwritten

export type TypeDefinitionFile = {
  path: string,
  content: string,
};

export const BUNDLED_TYPE_DEFINITIONS: TypeDefinitionFile[] = ${JSON.stringify(bundledFiles, null, 2)};

export const BUNDLED_DASHBOARD_UI_TYPES: string = ${JSON.stringify(dashboardUITypes)};
`;
  
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  writeFileSyncIfChanged(outputPath, output);
  
  console.log(`[Bundle Type Definitions] Generated ${outputPath}`);
  console.log(`[Bundle Type Definitions] Total size: ${(output.length / 1024).toFixed(2)} KB, ${bundledFiles.length} files bundled`);
}

main().catch((...args) => {
  console.error('[Bundle Type Definitions] ERROR! Failed to bundle type definitions:', ...args);
  process.exit(1);
});
