import { writeFileSyncIfChanged } from '@stackframe/stack-shared/dist/utils/fs';
import { glob } from 'glob';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';

type TypeDefinitionFile = {
  path: string,
  content: string,
};

async function main() {
  console.log('[Bundle Type Definitions] Finding Stack SDK type definition files...');
  
  const rootPath = path.resolve(process.cwd(), '../..');
  const stackAppPath = path.join(rootPath, 'packages/template/src/lib/stack-app');
  const outputPath = path.join(rootPath, 'apps/dashboard/src/generated/bundled-type-definitions.ts');
  
  const files = await glob(`${stackAppPath}/**/*.ts`, {
    ignore: [
      `${stackAppPath}/**/implementations/**`,
      `${stackAppPath}/**/utils/**`,
      `${stackAppPath}/**/*.d.ts`,
      `${stackAppPath}/**/global.css`,
    ],
  });
  files.sort();
  
  console.log(`[Bundle Type Definitions] Found ${files.length} type definition files`);
  
  const bundledFiles: TypeDefinitionFile[] = [];
  
  for (const filePath of files) {
    const relativePath = path.relative(stackAppPath, filePath);
    const content = await fs.readFile(filePath, 'utf8');
    
    bundledFiles.push({
      path: relativePath,
      content,
    });
  }

  // Bundle dashboard-ui-components type declarations (auto-generated by tsdown build)
  // The build produces per-file .d.ts files, so we concatenate all of them to give
  // the AI the full type definitions (not just the re-export barrel).
  let dashboardUITypes = '';
  try {
    const dashboardUIDistPath = path.join(rootPath, 'packages/dashboard-ui-components/dist');
    const dtsFiles = await glob(`${dashboardUIDistPath}/**/*.d.ts`, {
      ignore: [`${dashboardUIDistPath}/**/*.d.ts.map`],
    });
    dtsFiles.sort();

    const parts: string[] = [];
    for (const dtsFile of dtsFiles) {
      const content = await fs.readFile(dtsFile, 'utf8');
      parts.push(content);
    }
    let raw = parts.join('\n');

    // Deduplicate #region blocks
    const seenRegions = new Set<string>();
    const lines = raw.split('\n');
    const dedupedLines: string[] = [];
    let skipUntilEndRegion = false;
    let currentRegionKey = '';
    for (const line of lines) {
      const regionMatch = line.match(/^\/\/\s*#region\s+(.+)/);
      if (regionMatch) {
        currentRegionKey = regionMatch[1].trim();
        if (seenRegions.has(currentRegionKey)) {
          skipUntilEndRegion = true;
          continue;
        }
        seenRegions.add(currentRegionKey);
      }
      if (skipUntilEndRegion) {
        if (/^\/\/\s*#endregion/.test(line)) {
          skipUntilEndRegion = false;
        }
        continue;
      }
      dedupedLines.push(line);
    }
    raw = dedupedLines.join('\n');

    // Strip imports, exports, sourcemap comments
    raw = raw
      .replace(/^import\s+\*\s+as\s+.*$/gm, '')
      .replace(/^import\s+\{[^}]*\}\s+from\s+["'][^"']*["']\s*;?\s*$/gm, '')
      .replace(/^export\s*\{[^}]*\}\s*;?\s*$/gm, '')
      .replace(/^\/\/#\s*sourceMappingURL=.*$/gm, '');

    // Remove internal-only component type files
    const internalComponents = ['cursor-blast-effect.d.ts', 'edit-mode.d.ts', 'resize-handle.d.ts'];
    for (const internal of internalComponents) {
      const regex = new RegExp(`\\/\\/\\s*#region\\s+${internal.replace('.', '\\.')}[\\s\\S]*?\\/\\/\\s*#endregion[^\\n]*`, 'g');
      raw = raw.replace(regex, '');
    }

    // Collapse multiple blank lines
    raw = raw.replace(/\n{3,}/g, '\n\n').trim();

    dashboardUITypes = raw;
    console.log(`[Bundle Type Definitions] Loaded dashboard-ui-components types from ${dtsFiles.length} .d.ts files (${(dashboardUITypes.length / 1024).toFixed(2)} KB)`);
  } catch {
    console.warn('[Bundle Type Definitions] Warning: dashboard-ui-components dist not found. Run the package build first.');
  }
  
  console.log('[Bundle Type Definitions] Generating bundled-type-definitions.ts...');
  
  const output = `// This file is auto-generated by scripts/bundle-type-definitions.ts
// Do not edit manually - changes will be overwritten

export type TypeDefinitionFile = {
  path: string,
  content: string,
};

export const BUNDLED_TYPE_DEFINITIONS: TypeDefinitionFile[] = ${JSON.stringify(bundledFiles, null, 2)};

export const BUNDLED_DASHBOARD_UI_TYPES: string = ${JSON.stringify(dashboardUITypes)};
`;
  
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  writeFileSyncIfChanged(outputPath, output);
  
  console.log(`[Bundle Type Definitions] Generated ${outputPath}`);
  console.log(`[Bundle Type Definitions] Total size: ${(output.length / 1024).toFixed(2)} KB, ${bundledFiles.length} files bundled`);
}

main().catch((...args) => {
  console.error('[Bundle Type Definitions] ERROR! Failed to bundle type definitions:', ...args);
  process.exit(1);
});
