export type AgentAuthIdentityType = "anonymous" | "service_auth";

export const AGENT_AUTH_SCOPES_SUPPORTED = ["agent.auth"] as const;

export const AGENT_AUTH_EVENTS_SUPPORTED = [
  "https://schemas.workos.com/events/agent/auth/identity/assertion/revoked",
] as const;

export function getAgentAuthIdentityTypesSupported(config: {
  agentAuth: {
    identityTypes: {
      serviceAuth: boolean,
      anonymous: boolean,
    },
  },
}): AgentAuthIdentityType[] {
  const supported: AgentAuthIdentityType[] = [];
  if (config.agentAuth.identityTypes.anonymous) {
    supported.push("anonymous");
  }
  if (config.agentAuth.identityTypes.serviceAuth) {
    supported.push("service_auth");
  }
  return supported;
}

export function getAgentAuthProjectBaseUrl(apiUrl: string, projectId: string) {
  return new URL(`/api/v1/projects/${encodeURIComponent(projectId)}`, apiUrl).toString().replace(/\/$/, "");
}

export function getAgentAuthProjectUrls(apiUrl: string, projectId: string) {
  const projectBaseUrl = getAgentAuthProjectBaseUrl(apiUrl, projectId);

  return {
    projectBaseUrl,
    resourceMetadataUrl: `${projectBaseUrl}/.well-known/oauth-protected-resource`,
    authorizationServerMetadataUrl: `${projectBaseUrl}/.well-known/oauth-authorization-server`,
    authMdUrl: `${projectBaseUrl}/auth.md`,
    identityEndpointUrl: `${projectBaseUrl}/agent/identity`,
    claimEndpointUrl: `${projectBaseUrl}/agent/identity/claim`,
    eventsEndpointUrl: `${projectBaseUrl}/agent/event/notify`,
    tokenEndpointUrl: `${projectBaseUrl}/agent/token`,
    revocationEndpointUrl: `${projectBaseUrl}/agent/revoke`,
    apiKeysEndpointUrl: `${projectBaseUrl}/agent/api-keys`,
  };
}

export function getAgentAuthClaimPageUrl(dashboardUrl: string, options: { claimAttemptToken: string, projectId: string }) {
  return new URL(`/projects/${encodeURIComponent(options.projectId)}/agent-auth-app/claim?claim_attempt_token=${encodeURIComponent(options.claimAttemptToken)}`, dashboardUrl).toString();
}

export function renderAgentAuthManifest(options: {
  projectName: string,
  resourceUrl: string,
  authorizationServerUrl: string,
  authMdUrl: string,
  identityEndpointUrl: string,
  claimEndpointUrl: string,
  claimPageUrl: string,
  eventsEndpointUrl: string,
  tokenEndpointUrl: string,
  revocationEndpointUrl: string,
  apiKeysEndpointUrl: string,
  apiKeysEnableUrl: string,
  accessTokenExpiresInSeconds: number,
  claimAttemptExpiresInSeconds: number,
  scopesSupported: readonly string[],
  identityTypesSupported: readonly AgentAuthIdentityType[],
  eventsSupported: readonly string[],
  resourceLogoUrl?: string | null,
}) {
  const identityTypesSupported = options.identityTypesSupported.length === 0
    ? ['- none']
    : options.identityTypesSupported.map((identityType) => `- ${identityType}`);

  const supportedScopes = options.scopesSupported.map((scope) => `- ${scope}`);
  const supportedEvents = options.eventsSupported.map((event) => `- ${event}`);

  return [
    `# AUTH.md for ${options.projectName}`,
    '',
    'This project supports **agentic registration** for the project-scoped agent-auth surface.',
    '',
    '## 1. Discover',
    '',
    'Fetch the project-scoped discovery documents first:',
    '',
    `- Protected resource metadata: \`${options.resourceUrl}\``,
    `- Authorization server metadata: \`${options.authorizationServerUrl}\``,
    '',
    `Then read the \`skill\` document at \`${options.authMdUrl}\` and follow the URLs it returns.`,
    '',
    '## 2. Choose a registration method',
    '',
    'Supported identity types:',
    '',
    ...identityTypesSupported,
    '',
    'Use `anonymous` when the agent can complete the flow later through a human claim.',
    'Use `service_auth` when the agent already knows the email address that will approve the claim.',
    '',
    '## 3. Register',
    '',
    '### Anonymous registration',
    '',
    `POST \`${options.identityEndpointUrl}\``,
    '',
    'Request:',
    '',
    '```json',
    '{ "type": "anonymous" }',
    '```',
    '',
    'Response:',
    '',
    '```json',
    '{',
    '  "registration": { "id": "reg_...", "type": "anonymous", "status": "pending", "expires_at": "2026-07-07T12:34:56.000Z" },',
    '  "identity_assertion": "refresh_token_like_value",',
    '  "assertion_expires": "2026-07-08T12:34:56.000Z",',
    '  "access_token": "stack_access_token",',
    '  "token_type": "Bearer",',
    `  "expires_in": ${options.accessTokenExpiresInSeconds},`,
    '  "claim_token": "claim_token_value",',
    '  "claim_token_expires_at": "2026-07-08T12:34:56.000Z",',
    '  "pre_claim_scopes": ["agent.auth"],',
    '  "post_claim_scopes": ["agent.auth"]',
    '}',
    '```',
    '',
    '### Service auth registration',
    '',
    `POST \`${options.identityEndpointUrl}\``,
    '',
    'Request:',
    '',
    '```json',
    '{ "type": "service_auth", "login_hint": "agent@example.com" }',
    '```',
    '',
    'Response:',
    '',
    '```json',
    '{',
    '  "registration": { "id": "reg_...", "type": "service_auth", "status": "pending", "expires_at": "2026-07-07T12:34:56.000Z" },',
    '  "claim_token": "claim_token_value",',
    '  "claim_token_expires_at": "2026-07-08T12:34:56.000Z",',
    '  "claim": {',
    '    "user_code": "123456",',
    `    "verification_uri": "${options.claimPageUrl}?claim_attempt_token=...",`,
    `    "verification_uri_complete": "${options.claimPageUrl}?claim_attempt_token=...&user_code=123456",`,
    '    "interval": 5,',
    `    "expires_in": ${options.claimAttemptExpiresInSeconds}`,
    '  },',
    `  "verification_uri": "${options.claimPageUrl}?claim_attempt_token=...",`,
    `  "verification_uri_complete": "${options.claimPageUrl}?claim_attempt_token=...&user_code=123456",`,
    '  "post_claim_scopes": ["agent.auth"]',
    '}',
    '```',
    '',
    'If the project disables a requested identity type, the server returns:',
    '',
    '- `service_auth_not_enabled`',
    '- `anonymous_not_enabled`',
    '',
    '## 4. Complete the claim ceremony',
    '',
    'When a human opens the verification URI, they sign in normally and enter the `user_code`.',
    'The dashboard claim page submits `claim_attempt_token` + `user_code` to:',
    '',
    `POST \`${options.claimEndpointUrl}/complete\``,
    '',
    'That endpoint returns the signed-in browser session tokens and finalizes the registration.',
    '',
    'Claim errors returned by the project:',
    '',
    '- `invalid_claim_token`',
    '- `claimed_or_in_flight`',
    '- `claim_expired`',
    '- `access_denied`',
    '',
    '## 5. Exchange',
    'After the claim is complete, obtain a fresh access token with the JWT-bearer grant:',
    '',
    `POST \`${options.tokenEndpointUrl}\``,
    '',
    '```json',
    '{',
    '  "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",',
    '  "assertion": "identity_assertion_refresh_token"',
    '}',
    '```',
    '',
    'Token responses always include:',
    '',
    '```json',
    '{',
    '  "token_type": "Bearer",',
    `  "expires_in": ${options.accessTokenExpiresInSeconds},`,
    '  "scope": "agent.auth",',
    '  "access_token": "...",',
    '  "identity_assertion": "...",',
    '  "assertion_expires": "2026-07-08T12:34:56.000Z"',
    '}',
    '```',
    '',
    'The claim grant also polls the same token endpoint:',
    '',
    '```json',
    '{',
    '  "grant_type": "urn:workos:agent-auth:grant-type:claim",',
    '  "claim_token": "claim_token_value"',
    '}',
    '```',
    '',
    'Poll responses may return:',
    '',
    '- `authorization_pending`',
    '- `slow_down`',
    '- `expired_token`',
    '- `invalid_grant`',
    '',
    '## 6. Use',
    '',
    'Send the minted access token in the HTTP `Authorization` header:',
    '',
    '```http',
    'Authorization: Bearer <access_token>',
    '```',
    '',
    '## 7. Issue a project API key',
    '',
    'When the agent needs a longer-lived API key, call:',
    '',
    `POST \`${options.apiKeysEndpointUrl}\``,
    '',
    'If the API Keys app or user API keys are disabled, the server returns:',
    '',
    '```json',
    '{',
    '  "error": "api_keys_app_not_enabled",',
    '  "error_description": "Agent API key issuance is not enabled for this project.",',
    `  "enable_url": "${options.apiKeysEnableUrl}"`,
    '}',
    '```',
    '',
    'If enabled, the endpoint reuses the normal user API key creation path and returns the same shape as the dashboard API Keys UI.',
    '',
    '## 8. Revoke',
    '',
    `POST \`${options.revocationEndpointUrl}\``,
    '',
    'Revoke the access token using RFC 7009 form data:',
    '',
    '```x-www-form-urlencoded',
    'token=<access_token>&token_type_hint=access_token',
    '```',
    '',
    'Revocation is idempotent. Stack Auth access tokens are stateless, so revoking one also invalidates the matching identity assertion. Re-register if you need a fresh assertion.',
    '',
    '## Supported scopes',
    '',
    ...supportedScopes,
    '',
    '## Supported events',
    '',
    ...supportedEvents,
    '',
    ...(options.resourceLogoUrl == null ? [] : ['## Resource logo', '', `- ${options.resourceLogoUrl}`, '']),
  ].join("\n");
}
