-- SPLIT_STATEMENT_SENTINEL
-- SINGLE_STATEMENT_SENTINEL
-- RUN_OUTSIDE_TRANSACTION_SENTINEL
DROP INDEX CONCURRENTLY IF EXISTS /* SCHEMA_NAME_SENTINEL */."ContactChannel_contactId_idx";
-- SPLIT_STATEMENT_SENTINEL

-- SINGLE_STATEMENT_SENTINEL
-- RUN_OUTSIDE_TRANSACTION_SENTINEL
CREATE INDEX CONCURRENTLY "ContactChannel_contactId_idx"
  ON /* SCHEMA_NAME_SENTINEL */."ContactChannel"("tenancyId", "contactId");
