// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  correlationId: __t.string().name("correlation_id"),
  createdAt: __t.timestamp().name("created_at"),
  mode: __t.string(),
  systemPromptId: __t.string().name("system_prompt_id"),
  quality: __t.string(),
  speed: __t.string(),
  modelId: __t.string().name("model_id"),
  isAuthenticated: __t.bool().name("is_authenticated"),
  projectId: __t.option(__t.string()).name("project_id"),
  userId: __t.option(__t.string()).name("user_id"),
  requestedToolsJson: __t.string().name("requested_tools_json"),
  messagesJson: __t.string().name("messages_json"),
  stepsJson: __t.string().name("steps_json"),
  finalText: __t.string().name("final_text"),
  inputTokens: __t.option(__t.u32()).name("input_tokens"),
  outputTokens: __t.option(__t.u32()).name("output_tokens"),
  cachedInputTokens: __t.option(__t.u32()).name("cached_input_tokens"),
  costUsd: __t.option(__t.f64()).name("cost_usd"),
  stepCount: __t.u32().name("step_count"),
  durationMs: __t.u64().name("duration_ms"),
  errorMessage: __t.option(__t.string()).name("error_message"),
  mcpCorrelationId: __t.option(__t.string()).name("mcp_correlation_id"),
  conversationId: __t.option(__t.string()).name("conversation_id"),
});
