// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  token: __t.string(),
  correlationId: __t.string(),
  mode: __t.string(),
  systemPromptId: __t.string(),
  quality: __t.string(),
  speed: __t.string(),
  modelId: __t.string(),
  isAuthenticated: __t.bool(),
  projectId: __t.option(__t.string()),
  userId: __t.option(__t.string()),
  requestedToolsJson: __t.string(),
  messagesJson: __t.string(),
  stepsJson: __t.string(),
  finalText: __t.string(),
  inputTokens: __t.option(__t.u32()),
  outputTokens: __t.option(__t.u32()),
  cachedInputTokens: __t.option(__t.u32()),
  costUsd: __t.option(__t.f64()),
  stepCount: __t.u32(),
  durationMs: __t.u64(),
  errorMessage: __t.option(__t.string()),
  mcpCorrelationId: __t.option(__t.string()),
  conversationId: __t.option(__t.string()),
};
