// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  correlationId: __t.string(),
  conversationId: __t.option(__t.string()),
  category: __t.string(),
  message: __t.string(),
  transport: __t.string(),
  requestIp: __t.option(__t.string()),
  requestIpSource: __t.option(__t.string()),
  userAgent: __t.option(__t.string()),
  requestHost: __t.option(__t.string()),
  mcpProtocolVersion: __t.option(__t.string()),
};
