// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  shard: __t.u8(),
  correlationId: __t.string().name("correlation_id"),
  createdAt: __t.timestamp().name("created_at"),
  conversationId: __t.option(__t.string()).name("conversation_id"),
  category: __t.string(),
  message: __t.string(),
  transport: __t.string(),
  requestIp: __t.option(__t.string()).name("request_ip"),
  requestIpSource: __t.option(__t.string()).name("request_ip_source"),
  userAgent: __t.option(__t.string()).name("user_agent"),
  requestHost: __t.option(__t.string()).name("request_host"),
  mcpProtocolVersion: __t.option(__t.string()).name("mcp_protocol_version"),
});
