// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  shard: __t.u8(),
  sourceMcpCorrelationId: __t.option(__t.string()).name("source_mcp_correlation_id"),
  question: __t.string(),
  answer: __t.string(),
  createdBy: __t.string().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  lastEditedBy: __t.string().name("last_edited_by"),
  lastEditedAt: __t.timestamp().name("last_edited_at"),
  published: __t.bool(),
  firstPublishedAt: __t.option(__t.timestamp()).name("first_published_at"),
  lastPublishedAt: __t.option(__t.timestamp()).name("last_published_at"),
});
