// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AiQueryLog = __t.object("AiQueryLog", {
  id: __t.u64(),
  shard: __t.u8(),
  correlationId: __t.string(),
  createdAt: __t.timestamp(),
  mode: __t.string(),
  systemPromptId: __t.string(),
  quality: __t.string(),
  speed: __t.string(),
  modelId: __t.string(),
  isAuthenticated: __t.bool(),
  projectId: __t.option(__t.string()),
  userId: __t.option(__t.string()),
  requestedToolsJson: __t.string(),
  messagesJson: __t.string(),
  stepsJson: __t.string(),
  finalText: __t.string(),
  inputTokens: __t.option(__t.u32()),
  outputTokens: __t.option(__t.u32()),
  cachedInputTokens: __t.option(__t.u32()),
  cacheCreationTokens: __t.option(__t.u32()),
  costUsd: __t.option(__t.f64()),
  cacheDiscountUsd: __t.option(__t.f64()),
  openrouterGenerationId: __t.option(__t.string()),
  stepCount: __t.u32(),
  durationMs: __t.u64(),
  errorMessage: __t.option(__t.string()),
  conversationId: __t.option(__t.string()),
});
export type AiQueryLog = __Infer<typeof AiQueryLog>;

export const EvalArtifact = __t.object("EvalArtifact", {
  id: __t.u64(),
  runId: __t.string(),
  stepRunId: __t.string(),
  path: __t.string(),
  contentType: __t.string(),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type EvalArtifact = __Infer<typeof EvalArtifact>;

export const EvalRun = __t.object("EvalRun", {
  id: __t.u64(),
  runId: __t.string(),
  workflowId: __t.string(),
  workflowName: __t.string(),
  label: __t.string(),
  model: __t.string(),
  status: __t.string(),
  sandboxId: __t.option(__t.string()),
  currentStepIndex: __t.u32(),
  totalSteps: __t.u32(),
  contextJson: __t.string(),
  configJson: __t.string(),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  startedAt: __t.option(__t.timestamp()),
  finishedAt: __t.option(__t.timestamp()),
});
export type EvalRun = __Infer<typeof EvalRun>;

export const EvalStepRun = __t.object("EvalStepRun", {
  id: __t.u64(),
  stepRunId: __t.string(),
  runId: __t.string(),
  stepIndex: __t.u32(),
  stepName: __t.string(),
  model: __t.string(),
  status: __t.string(),
  resultText: __t.string(),
  error: __t.option(__t.string()),
  numMessages: __t.u32(),
  costUsd: __t.option(__t.string()),
  inputTokens: __t.option(__t.u64()),
  outputTokens: __t.option(__t.u64()),
  cacheReadTokens: __t.option(__t.u64()),
  cacheCreationTokens: __t.option(__t.u64()),
  sessionId: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  startedAt: __t.option(__t.timestamp()),
  finishedAt: __t.option(__t.timestamp()),
});
export type EvalStepRun = __Infer<typeof EvalStepRun>;

export const EvalWorkflow = __t.object("EvalWorkflow", {
  id: __t.u64(),
  workflowId: __t.string(),
  name: __t.string(),
  description: __t.string(),
  stepsJson: __t.string(),
  defaultModel: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type EvalWorkflow = __Infer<typeof EvalWorkflow>;

export const EvalWorklog = __t.object("EvalWorklog", {
  id: __t.u64(),
  runId: __t.string(),
  stepRunId: __t.string(),
  seq: __t.u32(),
  kind: __t.string(),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type EvalWorklog = __Infer<typeof EvalWorklog>;

export const McpCallLog = __t.object("McpCallLog", {
  id: __t.u64(),
  shard: __t.u8(),
  correlationId: __t.string(),
  conversationId: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  toolName: __t.string(),
  reason: __t.string(),
  userPrompt: __t.string(),
  question: __t.string(),
  response: __t.string(),
  stepCount: __t.u32(),
  innerToolCallsJson: __t.string(),
  durationMs: __t.u64(),
  modelId: __t.string(),
  errorMessage: __t.option(__t.string()),
  qaReviewedAt: __t.option(__t.timestamp()),
  qaNeedsHumanReview: __t.option(__t.bool()),
  qaAnswerCorrect: __t.option(__t.bool()),
  qaAnswerRelevant: __t.option(__t.bool()),
  qaFlagsJson: __t.option(__t.string()),
  qaImprovementSuggestions: __t.option(__t.string()),
  qaOverallScore: __t.option(__t.u32()),
  qaReviewModelId: __t.option(__t.string()),
  qaConversationJson: __t.option(__t.string()),
  qaErrorMessage: __t.option(__t.string()),
  humanReviewedAt: __t.option(__t.timestamp()),
  humanReviewedBy: __t.option(__t.string()),
  humanCorrectedQuestion: __t.option(__t.string()),
  humanCorrectedAnswer: __t.option(__t.string()),
  publishedToQa: __t.bool(),
  publishedAt: __t.option(__t.timestamp()),
});
export type McpCallLog = __Infer<typeof McpCallLog>;

export const MyVisibleAiQueryLog = __t.object("MyVisibleAiQueryLog", {});
export type MyVisibleAiQueryLog = __Infer<typeof MyVisibleAiQueryLog>;

export const MyVisibleMcpCallLog = __t.object("MyVisibleMcpCallLog", {});
export type MyVisibleMcpCallLog = __Infer<typeof MyVisibleMcpCallLog>;

export const MyVisibleQaEntries = __t.object("MyVisibleQaEntries", {});
export type MyVisibleQaEntries = __Infer<typeof MyVisibleQaEntries>;

export const Operators = __t.object("Operators", {
  identity: __t.identity(),
  addedAt: __t.timestamp(),
  stackUserId: __t.string(),
  displayName: __t.string(),
});
export type Operators = __Infer<typeof Operators>;

export const PublishedQa = __t.object("PublishedQa", {});
export type PublishedQa = __Infer<typeof PublishedQa>;

export const PublishedQaRow = __t.object("PublishedQaRow", {
  id: __t.u64(),
  question: __t.string(),
  answer: __t.string(),
  publishedAt: __t.option(__t.timestamp()),
});
export type PublishedQaRow = __Infer<typeof PublishedQaRow>;

export const QaEntries = __t.object("QaEntries", {
  id: __t.u64(),
  shard: __t.u8(),
  sourceMcpCorrelationId: __t.option(__t.string()),
  requestId: __t.option(__t.string()),
  question: __t.string(),
  answer: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.timestamp(),
  lastEditedBy: __t.string(),
  lastEditedAt: __t.timestamp(),
  published: __t.bool(),
  firstPublishedAt: __t.option(__t.timestamp()),
  lastPublishedAt: __t.option(__t.timestamp()),
});
export type QaEntries = __Infer<typeof QaEntries>;
