// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  correlationId: __t.string(),
  inputTokens: __t.option(__t.u32()),
  outputTokens: __t.option(__t.u32()),
  cachedInputTokens: __t.option(__t.u32()),
  costUsd: __t.option(__t.f64()),
  cacheDiscountUsd: __t.option(__t.f64()),
};
