// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  correlationId: __t.string().name("correlation_id"),
  conversationId: __t.option(__t.string()).name("conversation_id"),
  createdAt: __t.timestamp().name("created_at"),
  toolName: __t.string().name("tool_name"),
  reason: __t.string(),
  userPrompt: __t.string().name("user_prompt"),
  question: __t.string(),
  response: __t.string(),
  stepCount: __t.u32().name("step_count"),
  innerToolCallsJson: __t.string().name("inner_tool_calls_json"),
  durationMs: __t.u64().name("duration_ms"),
  modelId: __t.string().name("model_id"),
  errorMessage: __t.option(__t.string()).name("error_message"),
  qaReviewedAt: __t.option(__t.timestamp()).name("qa_reviewed_at"),
  qaNeedsHumanReview: __t.option(__t.bool()).name("qa_needs_human_review"),
  qaAnswerCorrect: __t.option(__t.bool()).name("qa_answer_correct"),
  qaAnswerRelevant: __t.option(__t.bool()).name("qa_answer_relevant"),
  qaFlagsJson: __t.option(__t.string()).name("qa_flags_json"),
  qaImprovementSuggestions: __t.option(__t.string()).name("qa_improvement_suggestions"),
  qaOverallScore: __t.option(__t.u32()).name("qa_overall_score"),
  qaReviewModelId: __t.option(__t.string()).name("qa_review_model_id"),
  qaConversationJson: __t.option(__t.string()).name("qa_conversation_json"),
  qaErrorMessage: __t.option(__t.string()).name("qa_error_message"),
  humanReviewedAt: __t.option(__t.timestamp()).name("human_reviewed_at"),
  humanReviewedBy: __t.option(__t.string()).name("human_reviewed_by"),
  humanCorrectedQuestion: __t.option(__t.string()).name("human_corrected_question"),
  humanCorrectedAnswer: __t.option(__t.string()).name("human_corrected_answer"),
  publishedToQa: __t.option(__t.bool()).name("published_to_qa"),
  publishedAt: __t.option(__t.timestamp()).name("published_at"),
});
