import fs from "node:fs";
import path from "node:path";

const generatedFilePath = path.join("src", "private", "implementation.generated.ts");
const privateEnginePath = path.join("src", "private", "implementation", "index.ts");

function deindent(strings: TemplateStringsArray, ...values: unknown[]) {
  const value = strings.reduce((result, string, index) => {
    return result + string + (index < values.length ? String(values[index]) : "");
  }, "");
  const lines = value.split("\n");
  const nonEmptyLines = lines.filter(line => line.trim() !== "");
  const indent = Math.min(...nonEmptyLines.map(line => line.match(/^ */)?.[0].length ?? 0));
  return lines.map(line => line.slice(indent)).join("\n").trim();
}

function main() {
  const existingContents = fs.existsSync(generatedFilePath)
    ? fs.readFileSync(generatedFilePath, "utf8")
    : null;
  const generatedFileContents = deindent`
    // NOTE: This file is auto-generated by the generate-private-sign-up-risk-engine script. Do not edit it manually! Edit the implementation source files instead.
    export * from "../private/${fs.existsSync(privateEnginePath) ? "implementation" : "implementation-fallback"}/index";
  ` + "\n";

  if (existingContents !== generatedFileContents) {
    fs.writeFileSync(generatedFilePath, generatedFileContents);
    console.log("Successfully updated private sign-up risk engine entrypoint");
  } else {
    console.log("No changes needed to private sign-up risk engine entrypoint");
  }
}

main();
