-- SPLIT_STATEMENT_SENTINEL
-- SINGLE_STATEMENT_SENTINEL
-- RUN_OUTSIDE_TRANSACTION_SENTINEL
CREATE INDEX CONCURRENTLY IF NOT EXISTS "CliAuthAttempt_tenancyId_createdAt_id_idx"
  ON /* SCHEMA_NAME_SENTINEL */."CliAuthAttempt"("tenancyId", "createdAt" DESC, "id" DESC);
