// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  token: __t.string(),
  correlationId: __t.string(),
  conversationId: __t.option(__t.string()),
  toolName: __t.string(),
  reason: __t.string(),
  userPrompt: __t.string(),
  question: __t.string(),
  response: __t.string(),
  stepCount: __t.u32(),
  innerToolCallsJson: __t.string(),
  durationMs: __t.u64(),
  modelId: __t.string(),
  errorMessage: __t.option(__t.string()),
};
