// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  token: __t.string(),
  correlationId: __t.string(),
  qaNeedsHumanReview: __t.bool(),
  qaAnswerCorrect: __t.bool(),
  qaAnswerRelevant: __t.bool(),
  qaFlagsJson: __t.string(),
  qaImprovementSuggestions: __t.string(),
  qaOverallScore: __t.u32(),
  qaReviewModelId: __t.string(),
  qaConversationJson: __t.option(__t.string()),
  qaErrorMessage: __t.option(__t.string()),
};
