-- A service either builds from the deployment source's upload (rootDirectory /
-- dockerfilePath) or runs an already-built image named here. Nullable because
-- every existing row is a source build, which is also why there is no backfill:
-- NULL is exactly "built from source".
--
-- Left unconstrained on purpose. The exclusivity with rootDirectory /
-- dockerfilePath, and the requirement that the reference carry an explicit tag
-- or digest, are enforced in code with the rest of the definition rules (see
-- deploymentServiceDefinitionSchema) so that one place phrases them and one
-- error text reaches the author — the same choice made for isPublic's rules.
ALTER TABLE "DeploymentService" ADD COLUMN "image" TEXT;
