import { writeFileSyncIfChanged } from "@hexclave/shared/dist/utils/fs";
import { deindent } from "@hexclave/shared/dist/utils/strings";

const envVarsConfig: Record<string, { allowPublic?: boolean, deprecatedLegacyNames?: string[] }> = {
  HEXCLAVE_PORT_PREFIX: {
    allowPublic: true,
  },
  HEXCLAVE_PROJECT_ID: {
    allowPublic: true,
  },
  HEXCLAVE_PUBLISHABLE_CLIENT_KEY: {
    allowPublic: true,
  },
  HEXCLAVE_SECRET_SERVER_KEY: {},
  HEXCLAVE_SUPER_SECRET_ADMIN_KEY: {},
  HEXCLAVE_EXTRA_REQUEST_HEADERS: {
    allowPublic: true,
  },
  HEXCLAVE_API_URL_BROWSER: {
    allowPublic: true,
    deprecatedLegacyNames: ["BROWSER_STACK_API_URL", "BROWSER_HEXCLAVE_API_URL"],
  },
  HEXCLAVE_API_URL_SERVER: {
    allowPublic: true,
    deprecatedLegacyNames: ["SERVER_STACK_API_URL", "SERVER_HEXCLAVE_API_URL"],
  },
  HEXCLAVE_API_URL: {
    allowPublic: true,
    deprecatedLegacyNames: ["HEXCLAVE_URL", "STACK_URL"],
  },
  HEXCLAVE_HOSTED_HANDLER_DOMAIN_SUFFIX: {
    allowPublic: true,
  },
  HEXCLAVE_HOSTED_HANDLER_URL_TEMPLATE: {
    allowPublic: true,
  },
  HEXCLAVE_STRIPE_PUBLISHABLE_KEY: {
    allowPublic: true,
  },
  HEXCLAVE_BOT_CHALLENGE_SITE_KEY: {
    allowPublic: true,
  },
  HEXCLAVE_BOT_CHALLENGE_INVISIBLE_SITE_KEY: {
    allowPublic: true,
  },
  HEXCLAVE_IS_LOCAL_EMULATOR: {
    allowPublic: true,
  },
  HEXCLAVE_POSTHOG_KEY: {
    allowPublic: true,
  },
  HEXCLAVE_SVIX_SERVER_URL: {
    allowPublic: true,
  },
  HEXCLAVE_SENTRY_DSN: {
    allowPublic: true,
  },
  HEXCLAVE_VERSION_ALERTER_SEVERE_ONLY: {
    allowPublic: true,
  },
  NODE_ENV: {
    allowPublic: false,
  },
};

function getHexclaveEnvVarName(name: string): string | undefined {
  if (!name.includes("STACK_")) {
    return undefined;
  }
  return name.replace("STACK_", "HEXCLAVE_");
}

function getStackEnvVarName(name: string): string | undefined {
  if (!name.includes("HEXCLAVE_")) {
    return undefined;
  }
  return name.replace("HEXCLAVE_", "STACK_");
}

function getEnvVarSnippet(variableName: string) {
  return deindent`
    ((typeof process !== "undefined" ? process.env.${variableName} : undefined) || import.meta.env?.${variableName})
  `;
}

function getEnvVarCandidateSnippets(allVariables: string[]) {
  const allVariablesSet = new Set(allVariables);
  const emittedVariables = new Set<string>();
  const snippets: string[] = [];

  for (const variableName of allVariables) {
    if (emittedVariables.has(variableName)) {
      continue;
    }

    const stackName = getStackEnvVarName(variableName);
    if (stackName != null && allVariablesSet.has(stackName)) {
      emittedVariables.add(variableName);
      emittedVariables.add(stackName);
      snippets.push(deindent`
        resolveHexclaveStackEnvVar("${variableName}", "${stackName}", ${getEnvVarSnippet(variableName)}, ${getEnvVarSnippet(stackName)})
      `);
      continue;
    }

    const hexclaveName = getHexclaveEnvVarName(variableName);
    if (hexclaveName != null && allVariablesSet.has(hexclaveName)) {
      emittedVariables.add(hexclaveName);
      emittedVariables.add(variableName);
      snippets.push(deindent`
        resolveHexclaveStackEnvVar("${hexclaveName}", "${variableName}", ${getEnvVarSnippet(hexclaveName)}, ${getEnvVarSnippet(variableName)})
      `);
      continue;
    }

    emittedVariables.add(variableName);
    snippets.push(getEnvVarSnippet(variableName));
  }

  return snippets;
}

function generateEnvVarsConstSnippet() {
  const getters: string[] = [];
  for (const [key, config] of Object.entries(envVarsConfig)) {
    const allVariables = [key, ...(config.deprecatedLegacyNames ?? [])]
      .flatMap(k => k.startsWith("HEXCLAVE_") ? [k, k.replace("HEXCLAVE_", "STACK_")] : [k])
      .flatMap(k => config.allowPublic ? [k, `NEXT_PUBLIC_${k}`, `VITE_${k}`] : [k]);
    const candidateSnippets = getEnvVarCandidateSnippets(allVariables);
    // Use || (not ??) between candidates: empty-string env vars (e.g. the empty
    // HEXCLAVE_* placeholders in checked-in .env templates) must not shadow a
    // real value under a legacy STACK_* name further down the chain.
    getters.push(deindent`
      get ${key}() {
        return ${candidateSnippets.join("\n  || ")} || undefined;
      },
    `);
  }
  return deindent`
    // THIS FILE IS AUTO-GENERATED BY THE \`generate-env.ts\` SCRIPT.
    // DO NOT EDIT IT BY HAND.
    /* eslint-disable no-restricted-properties */

    function resolveHexclaveStackEnvVar(hexclaveName: string, stackName: string, hexclaveValue: string | undefined, stackValue: string | undefined): string | undefined {
      if (hexclaveValue && stackValue && hexclaveValue !== stackValue) {
        throw new Error(\`Environment variables \${hexclaveName} and \${stackName} are both set to different values. Remove one of them or set them to the same value.\`);
      }
      return hexclaveValue || stackValue || undefined;
    }

    export const envVars = {
      ${getters.join("\n")}
    };
  ` + "\n";
}

writeFileSyncIfChanged("src/generated/env.ts", generateEnvVarsConstSnippet());
