-- SPLIT_STATEMENT_SENTINEL
-- SINGLE_STATEMENT_SENTINEL
-- RUN_OUTSIDE_TRANSACTION_SENTINEL
CREATE INDEX CONCURRENTLY IF NOT EXISTS "WorkflowEvent_outbox_idx"
  ON /* SCHEMA_NAME_SENTINEL */."WorkflowEvent"("processedAt", "retryAt", "scheduledAt");
