// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/channels/growth.ts";
import * as module_2 from "../../agent/sandbox.ts";
import * as module_3 from "../../agent/tools/complete-interview.ts";
import * as module_4 from "../../agent/tools/create-action-item.ts";
import * as module_5 from "../../agent/tools/get-context-bundle.ts";
import * as module_6 from "../../agent/tools/get-metrics-context.ts";
import * as module_7 from "../../agent/tools/get-metrics.ts";
import * as module_8 from "../../agent/tools/get-project-context.ts";
import * as module_9 from "../../agent/tools/get-workflow-authoring-context.ts";
import * as module_10 from "../../agent/tools/present-interview-question.ts";
import * as module_11 from "../../agent/tools/record-adaptive-question.ts";
import * as module_12 from "../../agent/tools/save-artifact.ts";
import * as module_13 from "../../agent/tools/save-brief.ts";
import * as module_14 from "../../agent/tools/save-category-scores.ts";
import * as module_15 from "../../agent/tools/save-finding.ts";
import * as module_16 from "../../agent/tools/save-interview-questions.ts";
import * as module_17 from "../../agent/tools/save-note.ts";
import * as module_18 from "../../agent/tools/save-report.ts";
import * as module_19 from "../../agent/tools/sql-query.ts";
import * as module_20 from "../../agent/tools/validate-workflow.ts";
import * as module_21 from "../../agent/subagents/data-analyst/agent.ts";
import * as module_22 from "../../agent/subagents/data-analyst/sandbox.ts";
import * as module_23 from "../../agent/subagents/data-analyst/tools/get-metrics-context.ts";
import * as module_24 from "../../agent/subagents/data-analyst/tools/get-metrics.ts";
import * as module_25 from "../../agent/subagents/data-analyst/tools/save-findings.ts";
import * as module_26 from "../../agent/subagents/data-analyst/tools/save-notes.ts";
import * as module_27 from "../../agent/subagents/data-analyst/tools/sql-query.ts";
import * as module_28 from "../../agent/subagents/report-composer/agent.ts";
import * as module_29 from "../../agent/subagents/report-composer/sandbox.ts";
import * as module_30 from "../../agent/subagents/report-composer/tools/get-context-bundle.ts";
import * as module_31 from "../../agent/subagents/report-composer/tools/get-workflow-authoring-context.ts";
import * as module_32 from "../../agent/subagents/report-composer/tools/save-artifact.ts";
import * as module_33 from "../../agent/subagents/report-composer/tools/save-category-scores.ts";
import * as module_34 from "../../agent/subagents/report-composer/tools/save-report.ts";
import * as module_35 from "../../agent/subagents/report-composer/tools/validate-workflow.ts";
import * as module_36 from "../../agent/subagents/website-research/agent.ts";
import * as module_37 from "../../agent/subagents/website-research/sandbox.ts";
import * as module_38 from "../../agent/subagents/website-research/tools/browse-page.ts";
import * as module_39 from "../../agent/subagents/website-research/tools/capture-homepage-screenshot.ts";
import * as module_40 from "../../agent/subagents/website-research/tools/get-project-context.ts";
import * as module_41 from "../../agent/subagents/website-research/tools/save-brand-kit.ts";
import * as module_42 from "../../agent/subagents/website-research/tools/save-crawl-summary.ts";
import * as module_43 from "../../agent/subagents/website-research/tools/save-findings.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/growth.ts": module_1,
                  "sandbox.ts": module_2,
                  "tools/complete-interview.ts": module_3,
                  "tools/create-action-item.ts": module_4,
                  "tools/get-context-bundle.ts": module_5,
                  "tools/get-metrics-context.ts": module_6,
                  "tools/get-metrics.ts": module_7,
                  "tools/get-project-context.ts": module_8,
                  "tools/get-workflow-authoring-context.ts": module_9,
                  "tools/present-interview-question.ts": module_10,
                  "tools/record-adaptive-question.ts": module_11,
                  "tools/save-artifact.ts": module_12,
                  "tools/save-brief.ts": module_13,
                  "tools/save-category-scores.ts": module_14,
                  "tools/save-finding.ts": module_15,
                  "tools/save-interview-questions.ts": module_16,
                  "tools/save-note.ts": module_17,
                  "tools/save-report.ts": module_18,
                  "tools/sql-query.ts": module_19,
                  "tools/validate-workflow.ts": module_20
                })
            }),
      "subagents/data-analyst": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_21,
                  "sandbox.ts": module_22,
                  "tools/get-metrics-context.ts": module_23,
                  "tools/get-metrics.ts": module_24,
                  "tools/save-findings.ts": module_25,
                  "tools/save-notes.ts": module_26,
                  "tools/sql-query.ts": module_27
                })
            }),
      "subagents/report-composer": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_28,
                  "sandbox.ts": module_29,
                  "tools/get-context-bundle.ts": module_30,
                  "tools/get-workflow-authoring-context.ts": module_31,
                  "tools/save-artifact.ts": module_32,
                  "tools/save-category-scores.ts": module_33,
                  "tools/save-report.ts": module_34,
                  "tools/validate-workflow.ts": module_35
                })
            }),
      "subagents/website-research": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_36,
                  "sandbox.ts": module_37,
                  "tools/browse-page.ts": module_38,
                  "tools/capture-homepage-screenshot.ts": module_39,
                  "tools/get-project-context.ts": module_40,
                  "tools/save-brand-kit.ts": module_41,
                  "tools/save-crawl-summary.ts": module_42,
                  "tools/save-findings.ts": module_43
                })
            })
    })
});

export default moduleMap;
