import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import {
  DASHBOARD_REFERENCE_APPS,
  getDashboardReferenceDocPath,
  listDashboardReferencePages,
} from "../packages/stack-shared/src/dashboard-docs";
import { writeFileSyncIfChanged } from "./utils";

const repoRoot = path.resolve(__dirname, "..");
const appsFrontendPath = path.join(repoRoot, "apps/dashboard/src/lib/apps-frontend.tsx");
const generatedMdxComment = "This file is auto-generated by scripts/generate-dashboard-reference-docs.ts. Do not edit it manually; edit packages/stack-shared/src/dashboard-docs/definitions.ts and the matching body file under packages/stack-shared/src/dashboard-docs/bodies/ instead.";
const bodiesRoot = path.join(repoRoot, "packages/stack-shared/src/dashboard-docs/bodies");
const mdxRoot = path.join(repoRoot, "docs-mintlify/guides/dashboard-references");
const docsJsonPath = path.join(repoRoot, "docs-mintlify/docs.json");

type DocsJson = {
  navigation: {
    tabs: Array<{
      tab: string,
      pages: unknown[],
    }>,
  },
  redirects: Array<{ source: string, destination: string }>,
};

function readBody(appId: string, slug: string): string {
  const bodyPath = path.join(bodiesRoot, appId, `${slug}.md`);
  if (!fs.existsSync(bodyPath)) {
    throw new Error(`Missing dashboard reference body file: ${bodyPath}`);
  }
  const body = fs.readFileSync(bodyPath, "utf-8");
  if (body.trim().length === 0) {
    throw new Error(`Dashboard reference body file is empty: ${bodyPath}`);
  }
  return body.replace(/\r\n/g, "\n").replace(/\n+$/, "") + "\n";
}

function renderMdx(
  page: { title: string, description: string, sidebarTitle?: string },
  body: string,
): string {
  const sidebarTitle = page.sidebarTitle ?? page.title;
  return [
    "---",
    "hidden: true",
    `title: ${JSON.stringify(page.title)}`,
    `description: ${JSON.stringify(page.description)}`,
    `sidebarTitle: ${JSON.stringify(sidebarTitle)}`,
    "---",
    "",
    `{/* ${generatedMdxComment} */}`,
    "",
    body.endsWith("\n") ? body : `${body}\n`,
  ].join("\n");
}

function buildDashboardReferenceNavGroup() {
  return {
    group: "Dashboard reference",
    hidden: true,
    searchable: true,
    pages: DASHBOARD_REFERENCE_APPS.map((app) => ({
      group: app.groupLabel,
      icon: app.icon,
      pages: app.pages.map((page) => getDashboardReferenceDocPath(app.appId, page.slug)),
    })),
  };
}

function patchDocsJson(dashboardReferenceNavGroup: ReturnType<typeof buildDashboardReferenceNavGroup>) {
  const docsJson = JSON.parse(fs.readFileSync(docsJsonPath, "utf-8")) as DocsJson;
  const documentationTab = docsJson.navigation.tabs.find((tab) => tab.tab === "Documentation");
  if (documentationTab == null) {
    throw new Error('docs.json: "Documentation" tab not found');
  }

  const pages = documentationTab.pages;
  const integrationsIndex = pages.findIndex(
    (entry) => typeof entry === "object" && entry != null && "group" in entry && (entry as { group: string }).group === "Integrations",
  );
  if (integrationsIndex === -1) {
    throw new Error('docs.json: "Integrations" group not found under Documentation');
  }

  const dashboardRefIndex = pages.findIndex(
    (entry) => typeof entry === "object" && entry != null && "group" in entry && (entry as { group: string }).group === "Dashboard reference",
  );

  const nextPages = [...pages];
  if (dashboardRefIndex === -1) {
    nextPages.splice(integrationsIndex, 0, dashboardReferenceNavGroup);
  } else {
    nextPages[dashboardRefIndex] = dashboardReferenceNavGroup;
  }

  documentationTab.pages = nextPages;

  const legacyRedirects: Array<{ source: string, destination: string }> = [];
  for (const { app, page } of listDashboardReferencePages()) {
    const legacySource = `/guides/apps/${app.appId}/${page.slug}`;
    const destination = `/${getDashboardReferenceDocPath(app.appId, page.slug)}`;
    legacyRedirects.push({ source: legacySource, destination });
  }

  const redirectSources = new Set(docsJson.redirects.map((r) => r.source));
  for (const redirect of legacyRedirects) {
    if (!redirectSources.has(redirect.source)) {
      docsJson.redirects.push(redirect);
      redirectSources.add(redirect.source);
    }
  }

  writeFileSyncIfChanged(docsJsonPath, `${JSON.stringify(docsJson, null, 2)}\n`);
}

/** Reads `navigationItems[].displayName` from apps-frontend.tsx without importing the dashboard bundle. */
function extractNavigationDisplayNamesFromAppsFrontend(appId: string): string[] {
  const content = fs.readFileSync(appsFrontendPath, "utf-8");
  const appKeyPattern = new RegExp(`\\n\\s*${appId.replace(/-/g, "\\-")}:\\s*\\{`);
  const appMatch = appKeyPattern.exec(content);
  if (appMatch == null) {
    throw new Error(`Could not find app "${appId}" in apps-frontend.tsx`);
  }

  const navItemsKeywordIndex = content.indexOf("navigationItems:", appMatch.index);
  if (navItemsKeywordIndex === -1) {
    throw new Error(`App "${appId}" has no navigationItems in apps-frontend.tsx`);
  }

  const arrayStart = content.indexOf("[", navItemsKeywordIndex);
  let depth = 0;
  let arrayEnd = -1;
  for (let i = arrayStart; i < content.length; i++) {
    if (content[i] === "[") {
      depth++;
    } else if (content[i] === "]") {
      depth--;
      if (depth === 0) {
        arrayEnd = i;
        break;
      }
    }
  }
  if (arrayEnd === -1) {
    throw new Error(`Could not parse navigationItems for app "${appId}" in apps-frontend.tsx`);
  }

  const navBlock = content.slice(arrayStart, arrayEnd + 1);
  const labels: string[] = [];
  const displayNamePattern = /displayName:\s*"([^"]+)"/g;
  let labelMatch = displayNamePattern.exec(navBlock);
  while (labelMatch != null) {
    labels.push(labelMatch[1]);
    labelMatch = displayNamePattern.exec(navBlock);
  }
  return labels;
}

function validateAgainstAppsFrontend() {
  for (const app of DASHBOARD_REFERENCE_APPS) {
    const navLabels = extractNavigationDisplayNamesFromAppsFrontend(app.appId);

    const documentedLabels = new Set(app.pages.map((p) => p.dashboardNavLabel));
    const allowedUndocumented = new Set(app.undocumentedDashboardNavLabels ?? []);

    for (const navLabel of navLabels) {
      if (documentedLabels.has(navLabel) || allowedUndocumented.has(navLabel)) {
        continue;
      }
      throw new Error(
        `Dashboard nav item "${navLabel}" on app "${app.appId}" has no dashboard reference doc. `
        + `Add a page in packages/stack-shared/src/dashboard-docs/definitions.ts or list it in undocumentedDashboardNavLabels.`,
      );
    }

    for (const page of app.pages) {
      if (!navLabels.includes(page.dashboardNavLabel)) {
        throw new Error(
          `Dashboard reference page "${app.appId}/${page.slug}" uses dashboardNavLabel "${page.dashboardNavLabel}" `
          + "but no matching navigationItems[].displayName exists in apps-frontend.tsx.",
        );
      }
    }
  }
}

function removeOrphanGeneratedMdx() {
  const expectedPaths = new Set(
    listDashboardReferencePages().map(({ app, page }) => path.join(mdxRoot, app.appId, `${page.slug}.mdx`)),
  );

  for (const app of DASHBOARD_REFERENCE_APPS) {
    const appDir = path.join(mdxRoot, app.appId);
    if (!fs.existsSync(appDir)) {
      continue;
    }
    for (const entry of fs.readdirSync(appDir)) {
      if (!entry.endsWith(".mdx")) {
        continue;
      }
      const fullPath = path.join(appDir, entry);
      if (!expectedPaths.has(fullPath)) {
        fs.unlinkSync(fullPath);
        console.log(`Removed orphan generated file: ${fullPath}`);
      }
    }
  }
}

function main() {
  validateAgainstAppsFrontend();

  const expectedMdxPaths = new Set<string>();
  for (const { app, page } of listDashboardReferencePages()) {
    const body = readBody(app.appId, page.slug);
    const mdxPath = path.join(mdxRoot, app.appId, `${page.slug}.mdx`);
    fs.mkdirSync(path.dirname(mdxPath), { recursive: true });
    writeFileSyncIfChanged(mdxPath, renderMdx(page, body));
    expectedMdxPaths.add(mdxPath);
  }

  removeOrphanGeneratedMdx();

  patchDocsJson(buildDashboardReferenceNavGroup());

  execSync("pnpm run generate-setup-prompt-docs", {
    cwd: repoRoot,
    stdio: "inherit",
  });

  console.log("Generated dashboard reference docs.");
}

main();
