-- Raw system events now write to ClickHouse's canonical telemetry table, but
-- automatically dropping the PostgreSQL source in the same release makes a
-- rollback impossible and turns an unnoticed backfill/cutover gap into data
-- loss. Keep both legacy tables intact and read-only. They can be removed by a
-- later, separately reviewed retention migration after production parity and
-- rollback-window checks have succeeded.
--
-- This migration is deliberately a no-op: removing the Prisma models stops new
-- application writes without taking an ACCESS EXCLUSIVE DROP lock or deleting
-- the only rollback copy of historical data.
-- SINGLE_STATEMENT_SENTINEL
SELECT 1;
