// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddManualQaReducer from "../add_manual_qa_reducer";
import AddOperatorReducer from "../add_operator_reducer";
import BackfillQaEntriesReducer from "../backfill_qa_entries_reducer";
import DeleteAiQueryLogReducer from "../delete_ai_query_log_reducer";
import DeleteMcpCallLogReducer from "../delete_mcp_call_log_reducer";
import DeleteQaEntryReducer from "../delete_qa_entry_reducer";
import EnrollServiceReducer from "../enroll_service_reducer";
import LogAiQueryReducer from "../log_ai_query_reducer";
import LogMcpCallReducer from "../log_mcp_call_reducer";
import MarkHumanReviewedReducer from "../mark_human_reviewed_reducer";
import RemoveOperatorReducer from "../remove_operator_reducer";
import SetQaPublishedReducer from "../set_qa_published_reducer";
import UnmarkHumanReviewedReducer from "../unmark_human_reviewed_reducer";
import UpdateAiQueryCostReducer from "../update_ai_query_cost_reducer";
import UpdateMcpQaReviewReducer from "../update_mcp_qa_review_reducer";
import UpdateQaEntryReducer from "../update_qa_entry_reducer";
import UpdateQaEntryWithPublishReducer from "../update_qa_entry_with_publish_reducer";
import UpsertQaFromCallReducer from "../upsert_qa_from_call_reducer";

export type AddManualQaParams = __Infer<typeof AddManualQaReducer>;
export type AddOperatorParams = __Infer<typeof AddOperatorReducer>;
export type BackfillQaEntriesParams = __Infer<typeof BackfillQaEntriesReducer>;
export type DeleteAiQueryLogParams = __Infer<typeof DeleteAiQueryLogReducer>;
export type DeleteMcpCallLogParams = __Infer<typeof DeleteMcpCallLogReducer>;
export type DeleteQaEntryParams = __Infer<typeof DeleteQaEntryReducer>;
export type EnrollServiceParams = __Infer<typeof EnrollServiceReducer>;
export type LogAiQueryParams = __Infer<typeof LogAiQueryReducer>;
export type LogMcpCallParams = __Infer<typeof LogMcpCallReducer>;
export type MarkHumanReviewedParams = __Infer<typeof MarkHumanReviewedReducer>;
export type RemoveOperatorParams = __Infer<typeof RemoveOperatorReducer>;
export type SetQaPublishedParams = __Infer<typeof SetQaPublishedReducer>;
export type UnmarkHumanReviewedParams = __Infer<typeof UnmarkHumanReviewedReducer>;
export type UpdateAiQueryCostParams = __Infer<typeof UpdateAiQueryCostReducer>;
export type UpdateMcpQaReviewParams = __Infer<typeof UpdateMcpQaReviewReducer>;
export type UpdateQaEntryParams = __Infer<typeof UpdateQaEntryReducer>;
export type UpdateQaEntryWithPublishParams = __Infer<typeof UpdateQaEntryWithPublishReducer>;
export type UpsertQaFromCallParams = __Infer<typeof UpsertQaFromCallReducer>;

