name: All good?

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  all-good:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
      checks: write
    steps:
      - name: Wait for 60 seconds
        run: sleep 6

      - name: Wait for all status checks to finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          COMMIT: ${{ github.sha }}
        run: |
          echo "Checking status checks for commit ${COMMIT} in repo ${REPO}..."
          echo "Checking status checks for commit ${COMMIT} in repo ${REPO}..."
          while true; do
            # Fetch Check Runs for the commit (Checks API)
            check_runs_response=$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              "https://api.github.com/repos/${REPO}/commits/${COMMIT}/check-runs")
            # Fetch legacy statuses for the commit (Statuses API)
            statuses_response=$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              "https://api.github.com/repos/${REPO}/commits/${COMMIT}/status")

            echo "Check runs response: $check_runs_response"
            echo "Statuses response: $statuses_response"

            # Determine total check runs from the Checks API
            total_check_runs=$(echo "$check_runs_response" | jq -r '.total_count')
            pending_check_runs=0
            if [ "$total_check_runs" -gt 0 ]; then
              pending_check_runs=$(echo "$check_runs_response" | jq '[.check_runs[] | select(.status != "completed")] | length')
            fi

            # For the legacy statuses, use the overall "state" field.
            overall_status=$(echo "$statuses_response" | jq -r '.state')
            
            echo "Pending check runs: $pending_check_runs; Legacy statuses overall state: $overall_status"

            # Wait if any check runs are still pending or if overall state is "pending"
            if [ "$pending_check_runs" -gt 0 ] || [ "$overall_status" = "pending" ]; then
              echo "Checks still in progress. Waiting..."
              sleep 10
              continue
            fi

            # If check runs exist, verify that all concluded with success.
            failed_check_runs=0
            if [ "$total_check_runs" -gt 0 ]; then
              failed_check_runs=$(echo "$check_runs_response" | jq '[.check_runs[] | select(.conclusion != "success")] | length')
            fi

            # Use the overall legacy status. If it's not "success", then consider it a failure.
            if [ "$overall_status" != "success" ]; then
              echo "Legacy statuses API returned overall state: ${overall_status}. Exiting with error."
              exit 1
            fi

            if [ "$failed_check_runs" -eq 0 ]; then
              echo "All status checks passed!"
              exit 0
            else
              echo "Some check runs failed. Exiting with error."
              exit 1
            fi
          done
