name: Wait for Check Runs

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  wait-for-checks:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      REPO: ${{ github.repository }}
      # Use the pull request head commit if available, otherwise default to the push commit SHA.
      COMMIT: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
    steps:
      - name: Wait for 60 seconds
        run: sleep 6

      - name: Poll Checks API until complete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking check runs for commit ${COMMIT} in repo ${REPO}..."
          while true; do
            response=$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              "https://api.github.com/repos/${REPO}/commits/${COMMIT}/check-runs")
            total=$(echo "$response" | jq -r '.total_count')

            echo "Response: $response"
            
            if [ "$total" -eq 0 ]; then
              echo "No check runs found for commit ${COMMIT}. Waiting..."
              sleep 10
              continue
            fi

            pending=$(echo "$response" | jq '[.check_runs[] | select(.status != "completed")] | length')
            if [ "$pending" -gt 0 ]; then
              echo "$pending check run(s) still in progress. Waiting..."
              sleep 10
              continue
            fi

            failed=$(echo "$response" | jq '[.check_runs[] | select(.conclusion != "success")] | length')
            if [ "$failed" -eq 0 ]; then
              echo "All check runs passed!"
              exit 0
            else
              echo "Some check runs failed. Exiting with error."
              exit 1
            fi
          done
